// @reza-ai/core — fondasi bersama Reza AI.
// Diimpor app lain via workspace:  import { prisma } from "@reza-ai/core";

export { prisma } from "./db.js";
export { createRedisClient, HEARTBEAT_KEY, QUEUE_PREFIX, isMockRedis } from "./redis.js";
export { QUEUE_NAMES, type QueueName } from "./queues.js";
export { nowWIB, isQuietHours, formatWIB, WIB_TIMEZONE } from "./time.js";
export { LEAD_STAGES, type LeadStage, isValidStage } from "./stages.js";
export {
  type WhatsAppGateway,
  type InboundMessage,
  type SendResult,
  type PresenceState,
} from "./gateway.js";
export { BaileysGateway, type BaileysGatewayOptions } from "./gateway-baileys.js";
export { FakeGateway } from "./gateway-fake.js";
export { normalizeJid, pnToJid, lidToJid, isGroupJid, isBroadcastJid, normalizePn } from "./wa-jid.js";
export {
  WA_STATUS_CHANNEL,
  WA_STATUS_LATEST_KEY,
  WA_RESTRICTED_KEY,
  publishWaStatus,
  getLatestWaStatus,
  setWaRestricted,
  isRestricted,
  type WaConnectionStatus,
  type WaStatusPayload,
} from "./wa-status.js";
export {
  WA_COMMAND_QUEUE,
  WA_COMMAND_FALLBACK_KEY,
  enqueueWaCommand,
  drainWaCommandFallback,
  peekWaCommandFallback,
  type WaCommand,
  type WaCommandPayload,
} from "./wa-command.js";
export { encryptSetting, decryptSetting } from "./crypto.js";
export {
  PROVIDER_SLOTS,
  SLOT_LABELS,
  apiKeySettingKey,
  inheritSettingKey,
  maskApiKey,
  parseModelList,
  getSettingDecrypted,
  setSettingEncrypted,
  getGeneralSettings,
  saveGeneralSettings,
  GENERAL_DEFAULTS,
  resolveEffectiveSlot,
  getEffectiveProviderConfig,
  listProviderSummaries,
  saveProviderSlot,
  type ProviderSlotName,
  type GeneralSettings,
  type SlotConfig,
  type ProviderSummary,
  type EffectiveProviderConfig,
  type SaveSlotInput,
} from "./providers.js";
export { hashPassword, verifyPassword, validatePasswordStrength, validateEmail } from "./password.js";
export { checkHealth, type HealthResult, type HealthStatus, type HealthDeps } from "./health.js";
export {
  INBOX_CHANNEL,
  INGEST_QUEUE,
  INGEST_FALLBACK_KEY,
  isPseudoPn,
  shouldIgnoreChat,
  processInboundMessage,
  publishInboxEvent,
  enqueueIngest,
  drainIngestFallback,
  startIngestFallbackPoller,
  type InboxEvent,
  type IgnoreInput,
  type ContactIdentity,
  type IngestDeps,
  type IngestResult,
} from "./ingest.js";
export {
  SEND_QUEUE,
  SEND_FALLBACK_KEY,
  SEND_PAUSE_KEY,
  SEND_LIMIT_PER_MINUTE,
  SEND_LIMIT_WINDOW_SEC,
  SendRateLimitedError,
  checkSendLimit,
  enqueueSend,
  drainSendFallback,
  processSendJob,
  startSendFallbackPoller,
  type SendContent,
  type SendJobPayload,
  type SendDeps,
} from "./send-queue.js";
export {
  CHARS_PER_TOKEN,
  CHUNK_TARGET_TOKENS,
  CHUNK_OVERLAP_TOKENS,
  EMBED_BATCH_SIZE,
  KNOWLEDGE_QUEUE,
  KNOWLEDGE_INGEST_KIND,
  REINDEX_QUEUE,
  REINDEX_FALLBACK_KEY,
  EMBEDDING_DIM_SETTING,
  DEFAULT_EMBEDDING_DIM,
  chunkText,
  splitSections,
  extractTextSource,
  extractUrlSource,
  extractPdfSource,
  embedBatch,
  vectorLiteral,
  ingestKnowledgeItem,
  hybridSearch,
  rrfFuse,
  reindexAll,
  getActiveEmbeddingDim,
  enqueueKnowledgeIngest,
  isKnowledgeIngestPayload,
  enqueueReindex,
  drainReindexFallback,
  startReindexFallbackPoller,
  maybeEnqueueReindex,
  type TextChunk,
  type TextSection,
  type ExtractedSource,
  type KnowledgeTypeName,
  type EmbedOpts,
  type KnowledgeDeps,
  type IngestKnowledgeResult,
  type HybridSearchHit,
  type HybridSearchOpts,
  type ReindexResult,
  type KnowledgeIngestPayload,
  type EnqueueResult,
} from "./knowledge.js";
export {
  PROMPT_HISTORY_LIMIT,
  REPLY_TEMPERATURE,
  CHAT_TIMEOUT_MS,
  SENSITIVE_INTENTS,
  detectSensitiveIntent,
  buildReplyPrompt,
  extractJsonObject,
  parseLlmReply,
  generateReply,
  type PersonaSpec,
  type HistoryMessage,
  type SensitiveIntent,
  type SensitiveIntentDef,
  type ReplyPromptInput,
  type ReplyPrompt,
  type LlmReply,
  type GenerateReplyInput,
  type AiEngineDeps,
  type ReplySource,
  type GenerateReplyResult,
} from "./ai-engine.js";
export {
  AI_REPLY_QUEUE,
  AI_REPLY_FALLBACK_KEY,
  AI_HISTORY_LIMIT,
  aiDebounceKey,
  aiRunLockKey,
  resolveMode,
  enqueueAiReply,
  scheduleAiReply,
  drainAiReplyFallback,
  startAiReplyFallbackPoller,
  notifyOwner,
  processAiReply,
  type AiMode,
  type AiReplyJobPayload,
  type AiPipelineDeps,
  type AiReplyOutcome,
} from "./ai-pipeline.js";
